### ISSUE TITLE
[Question] Do you plan to allow community apps in future?

### ISSUE THREAD

**Issue by csskevin** [hetznercloud/apps#17]
Great project. I really like it, but the choice of apps is small. It would be great to have more apps, for example Bitwarden, Owncloud, RabbitMQ etc. and I think with the community a lot of people would help you building those apps.

Do you plan to allow community apps in future, so that other developers can help you building custom apps?

**Comment by Flipez** [comment]
Hi @csskevin,

We do have a lot of ideas in mind for future app features (including community contributions). But since we just started with our apps we want to see how customers use it and what their feedback is.

Therefore I can not confirm anything but it is very likely that we will have a way for contribution in the future.
