### ISSUE TITLE
Add CloudPanel2

### ISSUE THREAD

**Issue by swieczorek** [hetznercloud/apps#52]
Hello Hetzner,

we from https://www.cloudpanel.io (german company) have released CloudPanel 2 with a special hetzner-cloud integration.

The CloudPanel community would love to see CloudPanel 2 as app in your cloud:

It would be a replacement for your LAMP Stack, cpanel and plesk:

https://www.dropbox.com/s/sghlenz4qh9wlz3/Screenshot%202022-06-24%20at%2015.03.52.png?dl=0

It's free and would be a huge benefit for your customers.

I would be happy to help you with that.

Other providers like Digital Ocean and VULTR have already added CloudPanel 2:

https://marketplace.digitalocean.com/apps/cloudpanel-2-ubuntu-22.04

https://www.vultr.com/marketplace/apps/cloudpanel2-ubuntu-2204

Best,
Stefan Wieczorek

**Comment by swieczorek** [comment]
Hi Flipez and Kjarrigan,
seems like there is a high demand for CloudPanel 2 on hetzner cloud :-)

**Comment by Flipez** [comment]
Hi @swieczorek 

Thank you for your issue. Unfortunately, as written in our [Readme](https://github.com/hetznercloud/apps#contributions) we currently do not accept new apps mostly due to time constraints. Therefore I have to reject this for now.

We will let you know once we change the rules here and accept contributions.

Cheers,
Robert
